"use client";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from "@react-three/drei";
import { useRef } from "react";
import { useFrame } from "@react-three/fiber";

export default function JPText(props) {
  const { nodes, materials } = useGLTF("/jp.glb");
  const modelRef = useRef(null);

  useFrame(({ mouse, viewport }) => {
    const x = (mouse.x * viewport.width) / 10;
    const y = (mouse.y * viewport.height) / 10;
    modelRef.current.lookAt(x, y, 1);
  });

  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          ref={modelRef}
          castShadow
          receiveShadow
          scale={1.8}
          geometry={nodes.Text.geometry}
          material={materials["Material.002"]}
          position={[0, 0, 0]}
          onPointerOut={() => modelRef.current.lookAt(0, 0, 1)}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/jp.glb");
