import "./globals.css";
import { Raleway, Open_Sans } from "next/font/google";
import classNames from "classnames";
import { Navbar } from "@/components/Navigation";
import Providers from "@/components/Providers";
import {
  AiFillFacebook,
  AiFillLinkedin,
  AiFillGithub,
  AiFillMail,
  AiFillFileText,
} from "react-icons/ai";

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});
const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
  weight: ["300", "400", "500", "600", "700", "800"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body className={classNames(openSans.variable, raleway.variable)}>
          <main className="mx-auto flex flex-col gap-10 p-6 md:flex-row md:gap-20 md:px-12 md:py-0">
            <div
              className="top-0 flex w-full max-w-[480px] flex-col gap-4 md:sticky 
              md:h-screen md:justify-between md:py-12"
            >
              <Navbar />
              <div className="flex flex-col gap-4">
                <div className="flex flex-col font-display text-6xl font-extrabold uppercase leading-none tracking-tight">
                  <p className="max-w-[40vw] text-cerulean-blue-500">
                    John Paul
                  </p>
                  <p>Zoleta</p>
                </div>
                <p className="font-display text-3xl font-bold">Web Developer</p>
              </div>
              <ul className="hidden flex-col gap-4 uppercase md:flex">
                <li>
                  <p>About</p>
                </li>
                <li>
                  <p>Works</p>
                </li>
                <li>
                  <p>Contact</p>
                </li>
              </ul>
              <div
                className="mt-10 flex h-[44px] w-fit items-center gap-6
              rounded-full bg-black px-6 text-white dark:bg-white dark:text-black"
              >
                <AiFillFacebook size={20} />
                <AiFillGithub size={20} />
                <AiFillLinkedin size={20} />
                <AiFillMail size={20} />
                <AiFillFileText size={20} />
              </div>
            </div>
            {children}
          </main>
        </body>
      </Providers>
    </html>
  );
}
